/* eslint-disable max-len */
module.exports = {
  vi: {
    sectionServices: 'Dịch vụ',
    navFinConsult: 'Tư vấn tài chính',
    sectionFinancing: 'Yêu cầu tài trợ',
    navContact: 'Liên hệ',
    servicesLead: 'Được cấu trúc cho chính phủ, tổ chức, doanh nghiệp, quỹ, family office và phi lợi nhuận — <strong>theo thứ tự ưu tiên</strong> từ ủy nhiệm của Quỹ: trước hết tư vấn và nghiên cứu, sau đó vốn và hòa giải, quản trị, chương trình ngành và kênh hỗ trợ.',
    servicesInstitutionalHint: 'Tư vấn, tài trợ và khả thi cần hợp đồng và KYC riêng — <strong>không</strong> được ngầm hiểu khi duyệt web hay dùng công cụ miễn phí. Xem <a href="#trust-entry">Tin cậy và lộ trình</a> · <a href="#terms">Điều khoản</a>.',
    servicesAudienceLead: 'Đối tác điển hình:',
    servicesChipGov: 'Chính phủ và chủ thể công',
    servicesChipCompanies: 'Doanh nghiệp và nhà thầu',
    servicesChipInvestors: 'Nhà đầu tư và tổ chức',
    servicesJumpLabel: 'Trên trang này',
    servicesJumpBot: 'Tổng quan BOT',
    servicesJumpCards: 'Danh mục dịch vụ',
    servicesJumpCompliance: 'Tuân thủ',
    servicesTrustKicker: 'Hợp tác thể chế chịu ràng buộc bởi hợp đồng và KYC — xem <a href="#trust-entry">Tin cậy và lộ trình</a> và <a href="#compliance">Tuân thủ</a>.',
    servicesCatalogJump: 'Chuyển tới <strong>dan mục 14 dịch vụ</strong> →',
    servicesStickyNavAria: 'Dịch vụ — liên kết nhanh trên trang này',
    govBotBadge: 'BOT',
    govBotTitle: 'BOT chính phủ — ô dù do Quỹ dẫn dắt',
    govBotBullet1: 'Đóng vai trò <strong>ô dù trung tâm</strong> cho một hoặc nhiều nước chủ nhà trong cấu trúc kiểu BOT.',
    govBotBullet2: '<strong>Quản lý triển khai</strong> với các công ty toàn cầu có năng lực thực thi đã được chứng minh.',
    govBotBullet3: '<strong>Huy động ngân hàng và tổ chức tài trợ dự án</strong> có thể cấp vốn và chấp nhận mô hình BOT/dự án.',
    govBotBullet4: 'Căn chỉnh vai trò và lợi ích giữa <strong>chính phủ, nhà thầu, bên tài trợ và Quỹ</strong> dưới khung quản trị rõ ràng.',
    govBotComplianceLink: 'Tuân thủ, giấy phép và AML/CFT →',
    servicesComplianceLinkHint: 'Liên kết nhảy tới mục Tuân thủ và giấy phép trên trang này (đăng ký, bối cảnh minh bạch và tham chiếu AML/CFT).',
    servicesNoteCore: '<strong>Cũng là cốt lõi của Quỹ:</strong> <strong>chuỗi dự án đầu tư</strong> tích cực, <strong>hòa giải</strong> giữa bên tài trợ và người thụ hưởng (gồm giao dịch xuyên biên giới) và <strong>tiếp cận công ty và nhà đầu tư toàn cầu</strong> — xem mục dự án và kênh liên hệ bên dưới.',
    servicesNoteHint: 'Mỗi thẻ mở mục liên quan: biểu mẫu, dự án, quản trị, ngành hoặc chương trình.',
    servicesBriefDisclaimer: 'Mô tả dịch vụ mang tính thông tin; phạm vi ràng buộc theo hợp đồng, KYC và pháp luật hiện hành — xem Điều khoản.',
    servicesGridKicker: 'Chọn một thẻ bên dưới để mở mục liên quan — <strong>biểu mẫu</strong>, <strong>ngành</strong>, <strong>quản trị</strong> hoặc <strong>liên hệ</strong>.',
    svc01Title: '1 · Tư vấn tài chính',
    svc01Desc: 'Hoạch định vốn, tái cơ cấu nợ và doanh nghiệp, định giá — cho khách hàng khu vực công, tư và phi lợi nhuận.',
    svc02Title: '2 · Nghiên cứu và khả thi',
    svc02Desc: 'Nghiên cứu kỹ thuật, kinh tế và tài chính cho dự án và đầu tư.',
    svc03Title: '3 · Vốn và tài trợ',
    svc03Desc: 'Huy động và cấu trúc vốn từ chính phủ, ngân hàng, quỹ và nhà đầu tư cho dự án và việc làm.',
    svc04Title: '4 · Dự án đầu tư và tiếp cận toàn cầu',
    svc04Desc: 'Chuỗi cho chương trình chính phủ và xuyên biên giới — gồm triển khai dưới <strong>ô dù BOT</strong>; thu hút nhà thầu và bên tài trợ toàn cầu (xem khối <strong>BOT chính phủ</strong> trong Dịch vụ).',
    svc05Title: '5 · Trung gian và giao dịch',
    svc05Desc: 'Trung gian giữa bên tài trợ và người thụ hưởng; môi giới thương mại, tài chính và giao dịch thương mại xuyên biên giới — gồm giới thiệu cấp dự án.',
    svc06Title: '6 · Mua bán và sáp nhập',
    svc06Desc: 'Phía mua/bán, thẩm định và hậu tích hợp sau sáp nhập cho nhiều loại thể chế.',
    svc07Title: '7 · Quản trị và hiệu suất',
    svc07Desc: 'Khung quản trị doanh nghiệp và hỗ trợ nâng cao hiệu suất thể chế.',
    svc08Title: '8 · Thành lập công ty và thể chế',
    svc08Desc: 'Thành lập thể chế tài chính, công nghiệp, nông nghiệp, công nghệ và an ninh; phòng thí nghiệm R&D khi phù hợp.',
    svc09Title: '9 · Xây dựng, vận hành và chuyển giao (BOT)',
    svc09Desc: 'Chương trình BOT chính phủ và đa phương: hạ tầng và tài sản xã hội dưới ô dù của Quỹ với đối tác thực thi toàn cầu.',
    svc10Title: '10 · Năng lượng và nước',
    svc10Desc: 'Khử muối nước biển, năng lượng sạch, lưới điện và đầu tư hiệu quả.',
    svc11Title: '11 · Công nghệ và AI',
    svc11Desc: 'Chuyển đổi số, an ninh mạng, chuyển giao công nghệ và R&D.',
    svc12Title: '12 · Niêm yết và thị trường vốn',
    svc12Desc: 'Cổ phiếu, sukuk và trái phiếu — phù hợp quy định áp dụng; công cụ có cấu trúc dùng kênh liên hệ.',
    svc13Title: '13 · Chuyển quỹ và tài sản có giá trị',
    svc13Desc: 'Di chuyển quỹ và tài sản có giá trị xuyên biên giới — tuân thủ chặt chẽ.',
    svc14Title: '14 · Đào tạo và nhân lực',
    svc14Desc: 'Đào tạo và nâng cao kỹ năng để tạo việc làm và giảm thất nghiệp.'
  },
  th: {
    sectionServices: 'บริการ',
    navFinConsult: 'ที่ปรึกษาทางการเงิน',
    sectionFinancing: 'คำขอรับการจัดหาเงินทุน',
    navContact: 'ติดต่อ',
    servicesLead: 'จัดโครงสร้างสำหรับรัฐบาล สถาบัน บริษัท กองทุน แฟมิลี่ออฟฟิศ และองค์กรไม่แสวงหากำไร — <strong>เรียงตามลำดับความสำคัญ</strong> ตามขอบเขตของกองทุน: ที่ปรึกษาและการศึกษาก่อน ตามด้วยเงินทุนและการไกล่เกลี่ย การกำกับดูแล โครงการภาคส่วน และช่องทางสนับสนุน',
    servicesInstitutionalHint: 'การให้คำปรึกษา การจัดหาเงินทุน และความเป็นไปได้ต้องมีสัญญาและ KYC แยกต่างหาก — <strong>ไม่</strong>ถือว่ามีโดยการเข้าชมเว็บหรือเครื่องมือฟรี ดู <a href="#trust-entry">ความไว้วางใจและเส้นทาง</a> · <a href="#terms">ข้อกำหนด</a>',
    servicesAudienceLead: 'คู่สัญญาที่พบบ่อย:',
    servicesChipGov: 'รัฐบาลและหน่วยงานของรัฐ',
    servicesChipCompanies: 'บริษัทและผู้รับเหมา',
    servicesChipInvestors: 'นักลงทุนและสถาบัน',
    servicesJumpLabel: 'ในหน้านี้',
    servicesJumpBot: 'ภาพรวม BOT',
    servicesJumpCards: 'แคตตาล็อกบริการ',
    servicesJumpCompliance: 'การปฏิบัติตามกฎ',
    servicesTrustKicker: 'การมีส่วนร่วมในระดับสถาบันถูกกำกับด้วยสัญญาและ KYC — ดู <a href="#trust-entry">ความไว้วางใจและเส้นทาง</a> และ <a href="#compliance">การปฏิบัติตามกฎ</a>',
    servicesCatalogJump: 'ไปยัง <strong>แคตตาล็อก 14 บริการ</strong> →',
    servicesStickyNavAria: 'บริการ — ลิงก์ด่วนในหน้านี้',
    govBotBadge: 'BOT',
    govBotTitle: 'BOT ภาครัฐ — ร่มนำโดยกองทุน',
    govBotBullet1: 'ทำหน้าที่เป็น <strong>ร่มกลาง</strong> สำหรับหนึ่งหรือหลายรัฐเจ้าภาพภายใต้โครงสร้างแบบ BOT',
    govBotBullet2: '<strong>บริหารการส่งมอบ</strong> ร่วมกับบริษัทระดับโลกที่มีความสามารถในการดำเนินการที่พิสูจน์แล้ว',
    govBotBullet3: '<strong>ระดมธนาคารและสถาบันจัดหาเงินทุนโครงการ</strong> ที่สามารถให้เงินและรับแบบจำลอง BOT/โครงการ',
    govBotBullet4: 'จัดให้บทบาทและผลประโยชน์สอดคล้องกันระหว่าง <strong>รัฐบาล ผู้รับเหมา ผู้ให้เงินทุน และกองทุน</strong> ภายใต้การกำกับดูแลที่ชัดเจน',
    govBotComplianceLink: 'การปฏิบัติตามกฎ ใบอนุญาต และ AML/CFT →',
    servicesComplianceLinkHint: 'ลิงก์ข้ามไปยังส่วนการปฏิบัติตามกฎและใบอนุญาตในหน้านี้ (การลงทะเบียน บริบทความโปร่งใส และอ้างอิง AML/CFT)',
    servicesNoteCore: '<strong>แก่นกลางของกองทุนยังรวมถึง:</strong> <strong>กลุ่มโครงการลงทุน</strong> ที่คล่องแคล่ว <strong>การไกล่เกลี่ย</strong> ระหว่างผู้ให้เงินทุนและผู้รับประโยชน์ (รวมข้อตกลงข้ามพรมแดน) และ <strong>การติดต่อบริษัทและนักลงทุนระดับโลก</strong> — ดูส่วนโครงการและช่องทางติดต่อด้านล่าง',
    servicesNoteHint: 'แต่ละการ์ดเปิดส่วนที่เกี่ยวข้อง: แบบฟอร์ม โครงการ การกำกับดูแล ภาคส่วน หรือโครงการ',
    servicesBriefDisclaimer: 'คำอธิบายบริการมีลักษณะให้ข้อมูล ขอบเขตที่ผูกพันตามสัญญา KYC และกฎหมายที่ใช้บังคับ — ดูข้อกำหนด',
    servicesGridKicker: 'เลือกการ์ดด้านล่างเพื่อเปิดส่วนที่เกี่ยวข้อง — <strong>แบบฟอร์ม</strong> <strong>ภาคส่วน</strong> <strong>การกำกับดูแล</strong> หรือ <strong>ติดต่อ</strong>',
    svc01Title: '1 · ที่ปรึกษาทางการเงิน',
    svc01Desc: 'วางแผนเงินทุน ปรับโครงสร้างหนี้และบริษัท และการประเมินมูลค่า — สำหรับลูกค้าภาครัฐ เอกชน และภาคที่สาม',
    svc02Title: '2 · การศึกษาและความเป็นไปได้',
    svc02Desc: 'การศึกษาทางเทคนิค เศรษฐศาสตร์ และการเงินสำหรับโครงการและการลงทุน',
    svc03Title: '3 · เงินทุนและการจัดหาเงินทุน',
    svc03Desc: 'ระดมและจัดโครงสร้างเงินทุนจากรัฐบาล ธนาคาร กองทุน และนักลงทุนสำหรับโครงการและงาน',
    svc04Title: '4 · โครงการลงทุนและการเชื่อมโยงทั่วโลก',
    svc04Desc: 'กลุ่มสำหรับโครงการภาครัฐและข้ามพรมแดน — รวมการส่งมอบภายใต้ <strong>ร่ม BOT</strong> ดึงดูดผู้รับเหมาและผู้ให้เงินทุนระดับโลก (ดูบล็อก <strong>BOT ภาครัฐ</strong> ในบริการ)',
    svc05Title: '5 · การเป็นตัวกลางและดีล',
    svc05Desc: 'ไกล่เกลี่ยระหว่างผู้ให้เงินทุนและผู้รับประโยชน์ เป็นตัวกลางการค้า การเงิน และธุรกรรมเชิงพาณิชย์ข้ามพรมแดน — รวมการแนะนำในระดับโครงการ',
    svc06Title: '6 · การควบรวมและซื้อกิจการ',
    svc06Desc: 'ฝั่งซื้อ/ขาย การตรวจสอบความเหมาะสม และการบูรณาการหลังควบรวมสำหรับประเภทนิติบุคคลต่างๆ',
    svc07Title: '7 · การกำกับดูแลและประสิทธิภาพ',
    svc07Desc: 'กรอบการกำกับดูแลกิจการและการสนับสนุนเพื่อยกระดับประสิทธิภาพของสถาบัน',
    svc08Title: '8 · การจัดตั้งบริษัทและนิติบุคคล',
    svc08Desc: 'จัดตั้งนิติบุคคลด้านการเงิน อุตสาหกรรม เกษตร เทคโนโลยี และความมั่นคง ห้องปฏิบัติการ R&D เมื่อเกี่ยวข้อง',
    svc09Title: '9 · ก่อสร้าง ดำเนินการ และโอน (BOT)',
    svc09Desc: 'โครงการ BOT ภาครัฐและพหุภาคี: โครงสร้างพื้นฐานและสินทรัพย์สังคมภายใต้ร่มของกองทุนกับพันธมิตรดำเนินงานระดับโลก',
    svc10Title: '10 · พลังงานและน้ำ',
    svc10Desc: 'การลดความเค็ม พลังงานสะอาด โครงข่าย และการลงทุนด้านประสิทธิภาพ',
    svc11Title: '11 · เทคโนโลยีและ AI',
    svc11Desc: 'การเปลี่ยนผ่านดิจิทัล ความปลอดภัยไซเบอร์ การถ่ายทอดเทคโนโลยี และ R&D',
    svc12Title: '12 · การจดทะเบียนและตลาดทุน',
    svc12Desc: 'หุ้น sukuk และพันธบัตร — สอดคล้องกฎที่ใช้บังคับ สำหรับตราสารโครงสร้างใช้ช่องทางติดต่อ',
    svc13Title: '13 · การโอนเงินและทรัพย์สินมีค่า',
    svc13Desc: 'การเคลื่อนไหวของเงินและทรัพย์สินมีค่าข้ามพรมแดน — ภายใต้การปฏิบัติตามกฎอย่างเข้มงวด',
    svc14Title: '14 · การฝึกอบรมและแรงงาน',
    svc14Desc: 'การฝึกอบรมและยกระดับทักษะเพื่อสร้างงานและลดการว่างงาน'
  }
};
