/* eslint-disable max-len */
module.exports = {
  am: {
    sectionServices: 'አገልግሎቶች',
    navFinConsult: 'የፋይናንስ አማካሪነት',
    sectionFinancing: 'የፋይናንስ ጥያቄ',
    navContact: 'አድራሻ',
    servicesLead: 'ለመንግስታት፣ ተቋማት፣ ኮርፖሬሽኖች፣ ፈንዶች፣ የቤተሰብ ቢሮዎች እና ለትርፍ ያልተቋቋሙ ድርጅቶች የተዋቀረ — ከፈንዱ ሥልጣን <strong>በቅድሚያ ቅደም ተከተል</strong>፦ መጀመሪያ አማካሪነት እና ጥናቶች፣ ከዚያ ካፒታል እና መካከለኛነት፣ አስተዳደር፣ የመስክ ፕሮግራሞች እና የድጋፍ መስመሮች።',
    servicesInstitutionalHint: 'አማካሪነት፣ ፋይናንስ እና ተግባራዊነት የተለዩ ውል እና KYC ይፈልጋሉ — በድር መፈለግ ወይም ነጻ መሳሪያዎች <strong>አይገልጹም</strong>። ይመልከቱ <a href="#trust-entry">እምነት እና መንገዶች</a> · <a href="#terms">ውሎች</a>።',
    servicesAudienceLead: 'ተለመዱ ተቃራኒዎች፦',
    servicesChipGov: 'መንግስታት እና የህዝብ አካላት',
    servicesChipCompanies: 'ኩባንያዎች እና ተቋራጮች',
    servicesChipInvestors: 'ኢንቨስተሮች እና ተቋማት',
    servicesJumpLabel: 'በዚህ ገጽ ላይ',
    servicesJumpBot: 'የBOT አጠቃላይ እይታ',
    servicesJumpCards: 'የአገልግሎት ካታሎግ',
    servicesJumpCompliance: 'መጣጣም',
    servicesTrustKicker: 'የተቋማዊ ተሳትፎ በውል እና KYC ይመራል — ይመልከቱ <a href="#trust-entry">እምነት እና መንገዶች</a> እና <a href="#compliance">መጣጣም</a>።',
    servicesCatalogJump: 'ወደ <strong>የ14 አገልግሎቶች ካታሎግ</strong> ይሂዱ →',
    servicesStickyNavAria: 'አገልግሎቶች — በዚህ ገጽ ላይ ፈጣን አገናኞች',
    govBotBadge: 'BOT',
    govBotTitle: 'የመንግስት BOT — በፈንዱ የሚመራ ጎራ',
    govBotBullet1: 'በBOT አይነት መዋቅሮች ለአንድ ወይም ለበርካታ አስተናጋጅ ሀገራት እንደ <strong>መሃል ጎራ</strong> መስራት።',
    govBotBullet2: 'የተረጋገጠ አፈጻጸም አቅም ካላቸው ዓለም አቀፍ ኩባንያዎች ጋር <strong>ማድረስን ማስተዳደር</strong>።',
    govBotBullet3: 'BOT/ፕሮጀክት ሞዴሎችን መደገፍ እና መቀበል የሚችሉ <strong>ባንኮች እና የፕሮጀክት ፋይናንስ ተቋማት</strong> ማነቃቃት።',
    govBotBullet4: 'በግልጽ አስተዳደር ስር በ<strong>መንግስታት፣ ተቋራጮች፣ ፋይናንሰሪዎች እና ፈንድ</strong> መካከል ሚናዎችን እና ጥቅሞችን ማስማማት።',
    govBotComplianceLink: 'መጣጣም፣ ፍቃዶች እና AML/CFT →',
    servicesComplianceLinkHint: 'አገናኙ ወደዚህ ገጽ ላይ የመጣጣም እና ፍቃዶች ክፍል ይወስዳል (መዝገቦች፣ ግልጽነት አውድ እና AML/CFT ማጣቀሻዎች)።',
    servicesNoteCore: '<strong>በፈንዱ ማዕከል ውስጥ ደግሞ፦</strong> ንቁ <strong>የኢንቨስትመንት ፕሮጀክቶች መስመር</strong>፣ በፋይናንሰሪዎች እና ተጠቃሚዎች መካከል <strong>መካከለኛነት</strong> (ድንበር ተሻጋሪ ስምምነቶችን ጨምሮ) እና <strong>ከዓለም አቀፍ ኩባንያዎች እና ኢንቨስተሮች ጋር መገናኘት</strong> — ከታች የፕሮጀክት ክፍል እና የአድራሻ መስመሮችን ይመልከቱ።',
    servicesNoteHint: 'እያንዳንዱ ካርድ የተዛመደውን ክፍል ይከፍታል፦ ቅጾች፣ ፕሮጀክቶች፣ አስተዳደር፣ መስኮች ወይም ፕሮግራሞች።',
    servicesBriefDisclaimer: 'የአገልግሎት መግለጫዎች መረጃ ብቻ ናቸው፤ የሚገዛው ወሰን ከውሎች፣ KYC እና ከሚሰራ ህግ ይመጣል — ውሎችን ይመልከቱ።',
    servicesGridKicker: 'የተዛመደውን ክፍል ለመክፈት ከታች ካርድ ይምረጡ — <strong>ቅጾች</strong>፣ <strong>መስኮች</strong>፣ <strong>አስተዳደር</strong> ወይም <strong>አድራሻ</strong>።',
    svc01Title: '1 · የፋይናንስ አማካሪነት',
    svc01Desc: 'የካፒታል እቅድ፣ ዕዳ እና ኮርፖሬት እንደገና ድርጅት እና ግምቶች — ለየህዝብ፣ የግል እና ለሶስተኛው መስክ ደንበኞች።',
    svc02Title: '2 · ጥናቶች እና ተግባራዊነት',
    svc02Desc: 'ለፕሮጀክቶች እና ኢንቨስትመንት ቴክኒካዊ፣ ኢኮኖሚ እና ፋይናንሳዊ ጥናቶች።',
    svc03Title: '3 · ካፒታል እና ፋይናንስ',
    svc03Desc: 'ከመንግስታት፣ ባንኮች፣ ፈንዶች እና ኢንቨስተሮች ለፕሮጀክቶች እና ለስራ ቦታዎች ካፒታል ማነቃቃት እና መዋቅር።',
    svc04Title: '4 · የኢንቨስትመንት ፕሮጀክቶች እና ዓለም አቀፍ ርዝመት',
    svc04Desc: 'ለመንግስታዊ እና ድንበር ተሻጋሪ ፕሮግራሞች መስመር — በ<strong>BOT ጎራ</strong> ስር ማድረስን ጨምሮ፤ ዓለም አቀፍ ተቋራጮችን እና ፋይናንሰሪዎችን መሳብ (በአገልግሎቶች ውስጥ <strong>የመንግስት BOT</strong> ብሎክ ይመልከቱ)።',
    svc05Title: '5 · መካከለኛነት እና ስምምነቶች',
    svc05Desc: 'በፋይናንሰሪዎች እና ተጠቃሚዎች መካከል መካከለኛነት፣ በንግድ፣ ፋይናንስ እና ንግድ ስምምነቶች ድንበር ተሻጋሪ ድርድር — የፕሮጀክት ደረጃ መግቢያዎችን ጨምሮ።',
    svc06Title: '6 · ውህደቶች እና ግዢዎች',
    svc06Desc: 'ገዢ/ሻጭ ጎን፣ due diligence እና ከውህደት በኋላ ውህደት ለተለያዩ አካል አይነቶች።',
    svc07Title: '7 · አስተዳደር እና አፈጻጸም',
    svc07Desc: 'የኮርፖሬት አስተዳደር ክፈፎች እና የተቋማዊ አፈጻጸም ማሻሻያ ድጋፍ።',
    svc08Title: '8 · ኩባንያ እና አካል ማቋቋም',
    svc08Desc: 'ፋይናንሳዊ፣ ኢንዱስትሪያል፣ ግብርና፣ ቴክኖሎጂ እና ደህንነት አካላት ማቋቋም፣ አስፈላጊ ከሆነ R&D ላቦራቶሪዎች።',
    svc09Title: '9 · ግንባታ፣ አሠራር እና ማስተላለፍ (BOT)',
    svc09Desc: 'መንግስታዊ እና ባለብዙ ጎን BOT ፕሮግራሞች፦ መሠረተ ልማት እና ማህበራዊ ንብረቶች በፈንዱ ጎራ ስር ከዓለም አቀፍ አፈጻጸም አጋሮች ጋር።',
    svc10Title: '10 · ኃይል እና ውሃ',
    svc10Desc: 'የጨው ማስወገድ፣ ንጹህ ኃይል፣ ግሪዶች እና ቅልጥፍና ኢንቨስትመንት።',
    svc11Title: '11 · ቴክኖሎጂ እና AI',
    svc11Desc: 'ዲጂታል ለውጥ፣ ሳይበር ደህንነት፣ ቴክኖሎጂ ማስተላለፍ እና R&D።',
    svc12Title: '12 · ዝርዝር እና የካፒታል ገበያዎች',
    svc12Desc: 'አክሲዮኖች፣ sukuk እና ቦንዶች — ከሚሰራ ደንብ ጋር፤ የተዋቀሩ መሳሪያዎች ለአድራሻ ይጠቀሙ።',
    svc13Title: '13 · ፈንዶች እና ዋጋ ያላቸው ንብረቶች ማስተላለፍ',
    svc13Desc: 'ድንበር ተሻጋሪ ፈንዶች እና ዋጋ ያላቸው ንብረቶች እንቅስቃሴ — በጠንካራ መጣጣም ስር።',
    svc14Title: '14 · ስልጠና እና የሰራተኛ ኃይል',
    svc14Desc: 'ስራ ለመፍጠር እና ስራ አጥነት ለመቀነስ ስልጠና እና ክህሎት ማሳደግ።'
  }
};
